site_name: 技术传播百态说
docs_dir: '../../docs/zh'
site_dir: '../../site/zh'
theme:
  name: material
  language: zh
  logo: assets/logo/logo_v3.svg
  favicon: assets/logo/favicon.ico
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
  custom_dir: ../../overrides

extra_css:
  - assets/stylesheets/palette.css
  - assets/stylesheets/page.css
  - assets/stylesheets/nav.css
  - assets/stylesheets/header.css
  - assets/stylesheets/footer.css

extra:
  homepage: https://www.tcblabber.cn/zh/
  doc_title: "米切尔轰炸机飞行员培训手册"
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: "简体中文"
      link: /zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wongyah/pilot_training_manual_for_mitchell_bomber
      name: "Pilot Training Manual for the Mitchell Bomber B-25"
    - icon: simple/wechat
      link: "https://mp.weixin.qq.com/s?__biz=MzA5NzU4ODAwOQ==&mid=2247487464&idx=1&sn=c57c1b993dcb2c166d88bc2c0d414a10&chksm=909fc9aea7e840b874ebe3e37d0e2a58de7c4c4c5e18f1355b1a4be6378b5752c571c4aeddd4&token=587590048&lang=zh_CN#rd"
      name: "微信公众号@技术传播百态说"
    - icon: simple/zhihu
      link: "https://www.zhihu.com/column/c_1548252009672929280"
      name: "知乎专栏@技术传播百态说"
    - icon: material/email
      link: "mailto:wongyah@126.com?subject=Markdown%20Syntax%20Hub"
      name: "我的邮箱"

copyright: "&copy; 2025 王烨."

nav:
  - 简介:
    - introduction/index.md
    - 历史: introduction/history_of_the_mitchell_bomber.md
    - introduction/duties_and_responsibilities_of_the_airplane_commander.md

markdown_extensions:
  - nl2br
  - abbr
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.blocks.html
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      base_path: snippets

